influx:
  url: https://influx.pycrs.cz
  token: "redacted"
  org: Homelab
  bucket: go-gas

vehicle-spawner:
  speed: [ 0ms ] # spawn rate in milliseconds
  goal: 100000

pumps:
  # pump-id:
  #   type: "electric | gas | diesel | hydrogen" (required)
  #   amount: 1 (required)
  #   speed: [1000, 5000] # random speed between 1-5s (single value or range) (required)
  regular_charger:
    name: Regular Charger
    type: electric
    amount: 1
    speed: [0ms]
  supercharger:
    name: Supercharger
    type: electric
    amount: 1
    speed: [ 0ms ]
  regular_diesel:
    name: Regular Diesel
    type: diesel
    amount: 2
    speed: [0ms]
  regular_gas:
    name: Regular Gas
    type: gas
    amount: 2
    speed: [0ms]
  regular_lpg:
    name: Regular LPG
    type: lpg
    amount: 1
    speed: [0ms]

registers:
  amount: 2
  speed: [0ms]