vehicle-spawner:
  rate: [ 10ms,20ms ] # spawn rate in milliseconds
  goal: 1000

pumps:
  # pump-id:
  #   type: "electric | gas | diesel | hydrogen" (required)
  #   amount: 1 (required)
  #   speed: [1000, 5000] # random speed between 1-5s (single value or range) (required)
  regular_charger:
    name: Regular Charger
    type: electric
    amount: 1
    speed: [100ms,200ms]
  regular_diesel:
    name: Regular Diesel
    type: diesel
    amount: 1
    speed: [10ms,50ms]
  regular_gas:
    name: Regular Gas
    type: gas
    amount: 1
    speed: [10ms,50ms]
  regular_lpg:
    name: Regular LPG
    type: lpg
    amount: 1
    speed: [15ms,30ms]

registers:
  amount: 1
  speed: [1000ms,2000ms]



